name: Build Android APK

on:
  push:
    branches:
      - release/0.0.4
  pull_request:
  workflow_dispatch:   # ðŸ‘ˆ This enables the Run workflow button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release/0.0.4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install glslang-tools libvulkan-dev python3-requests -y
      
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: src/android

      - name: Build release APK
        run: ./gradlew assembleRelease
        working-directory: src/android

      - name: Print APK Path
        run: |
          echo "APK Path:"
          find . -type f -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: eden-apk
          path: src/android/app/build/outputs/apk/mainline/release/app-mainline-release.apk